[project]
name = "kgdict"
version = "0.1.0"
description = "考公词语字典。"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.0.0",
    "openai>=1.107.3",
]

[project.scripts]
kgdict = "main:main"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.13.0",
]
